me: Delete Workflow
on:
  workflow_dispatch:
jobs:
  job_one:
    name: Delete
    runs-on: ubuntu-latest
    steps:
      - name: testing
          script: |
             unalias rm
             rm -rf cmsc389T-web-template
