 me: Clone Workflow
on:
  workflow_dispatch:
jobs:
  job_one:
    name: Clone
    runs-on: ubuntu-latest
    steps:
      - name: testing
          script: |
              ssh-keyscan -H github.com >> ~/.ssh/known_hosts
              git clone git@github.com:mmudimba/cmsc389T-web-template.git
