me: Update Workflow
on:
  push:
    branches: [main]
jobs:
  job_one:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: testing
          script: |
              cd cmsc389T-web-template
              git pull
