name: clone workflow
on: 
  workflow_dispatch:   
jobs:
  job_one:
    name: Clone
    runs-on: ubuntu-latest
    steps:
      - name: testing
        uses: appleboy/ssh-action@master
        with:
          host: terpconnect@umd.edu
          username: mmudimba
          password: Markmark8183
          port:  22
          script: |
              ssh-keyscan -H github.com > ~/.ssh/known_hosts
              cd ../pub
              git clone git@github.com:mmudimba/cmsc389T-web-template.git
