name: clone workflow
on: 
  workflow_dispatch:   
jobs:
  job_one:
    name: Clone
    runs-on: ubuntu-latest
    steps:
      - name: testing
        uses: appleboy/ssh-action@master
        with:
<<<<<<< HEAD
          host: terpconnect.umd.edu
          username: mmudimba
          password: Markmark8183
          port:  22
=======
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
>>>>>>> 653a69b710b9671c7b26aa0e113c5dc914609a8d
          script: |
              ssh-keyscan -H github.com >> ~/.ssh/known_hosts
              cd ../pub
              git clone git@github.com:mmudimba/cmsc389T-web-template.git
              
              
