name: Clean workflow
on: 
  workflow_dispatch:   
jobs:
  job_one:
    name: Clean
    runs-on: ubuntu-latest
    steps:
      - name: testing
        uses: appleboy/ssh-action@master
        with:
          host: terpconnect.umd.edu 
          username: mmudimba
          password: Markmark8183
          port: 22
          script: |
             cd ../pub
             unalias rm
             rm -rf cmsc389T-web-template 
