name: Update workflow
on: 
  push:
    branches: [main]
jobs:
  job_one:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: testing
        uses: appleboy/ssh-action@master
        with:
          host: terpconnect.umd.edu 
          username: mmudimba
          password: Markmark8183
          port: 22
          script: |
              cd ../pub    
              cd cmsc389T-web-template
              git pull
